/**
 * Yahoo Finance API module definitions and fundamental data options.
 */

export interface ModuleConfig {
  filter?: string;
  convert_dates: string[];
}

/**
 * Module configurations for quoteSummary endpoint.
 * Each module may have date fields that need conversion and optional filtering.
 */
export const MODULES_DICT: Record<string, ModuleConfig> = {
  assetProfile: {
    convert_dates: ['governanceEpochDate', 'compensationAsOfEpochDate'],
  },
  balanceSheetHistory: {
    filter: 'balanceSheetStatements',
    convert_dates: ['endDate'],
  },
  balanceSheetHistoryQuarterly: {
    filter: 'balanceSheetStatements',
    convert_dates: ['endDate'],
  },
  calendarEvents: {
    convert_dates: ['earningsDate', 'exDividendDate', 'dividendDate'],
  },
  cashflowStatementHistory: {
    filter: 'cashflowStatements',
    convert_dates: ['endDate'],
  },
  cashflowStatementHistoryQuarterly: {
    filter: 'cashflowStatements',
    convert_dates: ['endDate'],
  },
  defaultKeyStatistics: {
    convert_dates: [
      'sharesShortPreviousMonthDate',
      'dateShortInterest',
      'lastFiscalYearEnd',
      'nextFiscalYearEnd',
      'fundInceptionDate',
      'lastSplitDate',
      'mostRecentQuarter',
    ],
  },
  earnings: {
    convert_dates: ['earningsDate'],
  },
  earningsHistory: {
    filter: 'history',
    convert_dates: ['quarter'],
  },
  earningsTrend: {
    convert_dates: [],
  },
  esgScores: {
    convert_dates: [],
  },
  financialData: {
    convert_dates: [],
  },
  fundOwnership: {
    filter: 'ownershipList',
    convert_dates: ['reportDate'],
  },
  fundPerformance: {
    convert_dates: ['asOfDate'],
  },
  fundProfile: {
    convert_dates: [],
  },
  indexTrend: {
    convert_dates: [],
  },
  incomeStatementHistory: {
    filter: 'incomeStatementHistory',
    convert_dates: ['endDate'],
  },
  incomeStatementHistoryQuarterly: {
    filter: 'incomeStatementHistory',
    convert_dates: ['endDate'],
  },
  industryTrend: {
    convert_dates: [],
  },
  insiderHolders: {
    filter: 'holders',
    convert_dates: ['latestTransDate', 'positionDirectDate'],
  },
  insiderTransactions: {
    filter: 'transactions',
    convert_dates: ['startDate'],
  },
  institutionOwnership: {
    filter: 'ownershipList',
    convert_dates: ['reportDate'],
  },
  majorHoldersBreakdown: {
    convert_dates: [],
  },
  pageViews: {
    convert_dates: [],
  },
  price: {
    convert_dates: ['postMarketTime', 'preMarketTime', 'regularMarketTime'],
  },
  quoteType: {
    convert_dates: ['firstTradeDateEpochUtc'],
  },
  recommendationTrend: {
    filter: 'trend',
    convert_dates: [],
  },
  secFilings: {
    filter: 'filings',
    convert_dates: ['epochDate'],
  },
  netSharePurchaseActivity: {
    convert_dates: [],
  },
  sectorTrend: {
    convert_dates: [],
  },
  summaryDetail: {
    convert_dates: ['exDividendDate', 'expireDate', 'startDate'],
  },
  summaryProfile: {
    convert_dates: [],
  },
  topHoldings: {
    convert_dates: [],
  },
  upgradeDowngradeHistory: {
    filter: 'history',
    convert_dates: ['epochGradeDate'],
  },
};

/**
 * Fundamental data type options for financial statements.
 */
export const FUNDAMENTALS_OPTIONS: Record<string, string[]> = {
  income_statement: [
    'Amortization',
    'AmortizationOfIntangiblesIncomeStatement',
    'AverageDilutionEarnings',
    'BasicAccountingChange',
    'BasicAverageShares',
    'BasicContinuousOperations',
    'BasicDiscontinuousOperations',
    'BasicEPS',
    'BasicEPSOtherGainsLosses',
    'BasicExtraordinary',
    'ContinuingAndDiscontinuedBasicEPS',
    'ContinuingAndDiscontinuedDilutedEPS',
    'CostOfRevenue',
    'DepletionIncomeStatement',
    'DepreciationAmortizationDepletionIncomeStatement',
    'DepreciationAndAmortizationInIncomeStatement',
    'DepreciationIncomeStatement',
    'DilutedAccountingChange',
    'DilutedAverageShares',
    'DilutedContinuousOperations',
    'DilutedDiscontinuousOperations',
    'DilutedEPS',
    'DilutedEPSOtherGainsLosses',
    'DilutedExtraordinary',
    'DilutedNIAvailtoComStockholders',
    'DividendPerShare',
    'EBIT',
    'EBITDA',
    'EarningsFromEquityInterest',
    'EarningsFromEquityInterestNetOfTax',
    'ExciseTaxes',
    'GainOnSaleOfBusiness',
    'GainOnSaleOfPPE',
    'GainOnSaleOfSecurity',
    'GeneralAndAdministrativeExpense',
    'GrossProfit',
    'ImpairmentOfCapitalAssets',
    'InsuranceAndClaims',
    'InterestExpense',
    'InterestExpenseNonOperating',
    'InterestIncome',
    'InterestIncomeNonOperating',
    'MinorityInterests',
    'NetIncome',
    'NetIncomeCommonStockholders',
    'NetIncomeContinuousOperations',
    'NetIncomeDiscontinuousOperations',
    'NetIncomeExtraordinary',
    'NetIncomeFromContinuingAndDiscontinuedOperation',
    'NetIncomeFromContinuingOperationNetMinorityInterest',
    'NetIncomeFromTaxLossCarryforward',
    'NetIncomeIncludingNoncontrollingInterests',
    'NetInterestIncome',
    'NetNonOperatingInterestIncomeExpense',
    'NormalizedBasicEPS',
    'NormalizedDilutedEPS',
    'NormalizedEBITDA',
    'NormalizedIncome',
    'OperatingExpense',
    'OperatingIncome',
    'OperatingRevenue',
    'OtherGandA',
    'OtherIncomeExpense',
    'OtherNonOperatingIncomeExpenses',
    'OtherOperatingExpenses',
    'OtherSpecialCharges',
    'OtherTaxes',
    'OtherunderPreferredStockDividend',
    'PreferredStockDividends',
    'PretaxIncome',
    'ProvisionForDoubtfulAccounts',
    'ReconciledCostOfRevenue',
    'ReconciledDepreciation',
    'RentAndLandingFees',
    'RentExpenseSupplemental',
    'ReportedNormalizedBasicEPS',
    'ReportedNormalizedDilutedEPS',
    'ResearchAndDevelopment',
    'RestructuringAndMergernAcquisition',
    'SalariesAndWages',
    'SecuritiesAmortization',
    'SellingAndMarketingExpense',
    'SellingGeneralAndAdministration',
    'SpecialIncomeCharges',
    'TaxEffectOfUnusualItems',
    'TaxLossCarryforwardBasicEPS',
    'TaxLossCarryforwardDilutedEPS',
    'TaxProvision',
    'TaxRateForCalcs',
    'TotalExpenses',
    'TotalOperatingIncomeAsReported',
    'TotalOtherFinanceCost',
    'TotalRevenue',
    'TotalUnusualItems',
    'TotalUnusualItemsExcludingGoodwill',
    'WriteOff',
  ],
  balance_sheet: [
    'AccountsPayable',
    'AccountsReceivable',
    'AccruedInterestReceivable',
    'AccumulatedDepreciation',
    'AdditionalPaidInCapital',
    'AllowanceForDoubtfulAccountsReceivable',
    'AssetsHeldForSaleCurrent',
    'AvailableForSaleSecurities',
    'BuildingsAndImprovements',
    'CapitalLeaseObligations',
    'CapitalStock',
    'CashAndCashEquivalents',
    'CashCashEquivalentsAndShortTermInvestments',
    'CashEquivalents',
    'CashFinancial',
    'CommercialPaper',
    'CommonStock',
    'CommonStockEquity',
    'ConstructionInProgress',
    'CurrentAccruedExpenses',
    'CurrentAssets',
    'CurrentCapitalLeaseObligation',
    'CurrentDebt',
    'CurrentDebtAndCapitalLeaseObligation',
    'CurrentDeferredAssets',
    'CurrentDeferredLiabilities',
    'CurrentDeferredRevenue',
    'CurrentDeferredTaxesAssets',
    'CurrentDeferredTaxesLiabilities',
    'CurrentLiabilities',
    'CurrentNotesPayable',
    'CurrentProvisions',
    'DefinedPensionBenefit',
    'DerivativeProductLiabilities',
    'DividendsPayable',
    'DuefromRelatedPartiesCurrent',
    'DuefromRelatedPartiesNonCurrent',
    'DuetoRelatedPartiesCurrent',
    'DuetoRelatedPartiesNonCurrent',
    'EmployeeBenefits',
    'FinancialAssets',
    'FinancialAssetsDesignatedasFairValueThroughProfitorLossTotal',
    'FinishedGoods',
    'FixedAssetsRevaluationReserve',
    'ForeignCurrencyTranslationAdjustments',
    'GainsLossesNotAffectingRetainedEarnings',
    'GeneralPartnershipCapital',
    'Goodwill',
    'GoodwillAndOtherIntangibleAssets',
    'GrossAccountsReceivable',
    'GrossPPE',
    'HedgingAssetsCurrent',
    'HeldToMaturitySecurities',
    'IncomeTaxPayable',
    'InterestPayable',
    'InventoriesAdjustmentsAllowances',
    'Inventory',
    'InvestedCapital',
    'InvestmentProperties',
    'InvestmentinFinancialAssets',
    'InvestmentsAndAdvances',
    'InvestmentsInOtherVenturesUnderEquityMethod',
    'InvestmentsinAssociatesatCost',
    'InvestmentsinJointVenturesatCost',
    'InvestmentsinSubsidiariesatCost',
    'LandAndImprovements',
    'Leases',
    'LiabilitiesHeldforSaleNonCurrent',
    'LimitedPartnershipCapital',
    'LineOfCredit',
    'LoansReceivable',
    'LongTermCapitalLeaseObligation',
    'LongTermDebt',
    'LongTermDebtAndCapitalLeaseObligation',
    'LongTermEquityInvestment',
    'LongTermProvisions',
    'MachineryFurnitureEquipment',
    'MinimumPensionLiabilities',
    'MinorityInterest',
    'NetDebt',
    'NetPPE',
    'NetTangibleAssets',
    'NonCurrentAccountsReceivable',
    'NonCurrentAccruedExpenses',
    'NonCurrentDeferredAssets',
    'NonCurrentDeferredLiabilities',
    'NonCurrentDeferredRevenue',
    'NonCurrentDeferredTaxesAssets',
    'NonCurrentDeferredTaxesLiabilities',
    'NonCurrentNoteReceivables',
    'NonCurrentPensionAndOtherPostretirementBenefitPlans',
    'NonCurrentPrepaidAssets',
    'NotesReceivable',
    'OrdinarySharesNumber',
    'OtherCapitalStock',
    'OtherCurrentAssets',
    'OtherCurrentBorrowings',
    'OtherCurrentLiabilities',
    'OtherEquityAdjustments',
    'OtherEquityInterest',
    'OtherIntangibleAssets',
    'OtherInventories',
    'OtherInvestments',
    'OtherNonCurrentAssets',
    'OtherNonCurrentLiabilities',
    'OtherPayable',
    'OtherProperties',
    'OtherReceivables',
    'OtherShortTermInvestments',
    'Payables',
    'PayablesAndAccruedExpenses',
    'PensionandOtherPostRetirementBenefitPlansCurrent',
    'PreferredSecuritiesOutsideStockEquity',
    'PreferredSharesNumber',
    'PreferredStock',
    'PreferredStockEquity',
    'PrepaidAssets',
    'Properties',
    'RawMaterials',
    'Receivables',
    'ReceivablesAdjustmentsAllowances',
    'RestrictedCash',
    'RestrictedCommonStock',
    'RetainedEarnings',
    'ShareIssued',
    'StockholdersEquity',
    'TangibleBookValue',
    'TaxesReceivable',
    'TotalAssets',
    'TotalCapitalization',
    'TotalDebt',
    'TotalEquityGrossMinorityInterest',
    'TotalLiabilitiesNetMinorityInterest',
    'TotalNonCurrentAssets',
    'TotalNonCurrentLiabilitiesNetMinorityInterest',
    'TotalPartnershipCapital',
    'TotalTaxPayable',
    'TradeandOtherPayablesNonCurrent',
    'TradingSecurities',
    'TreasurySharesNumber',
    'TreasuryStock',
    'UnrealizedGainLoss',
    'WorkInProcess',
    'WorkingCapital',
  ],
  cash_flow: [
    'AdjustedGeographySegmentData',
    'AmortizationCashFlow',
    'AmortizationOfIntangibles',
    'AmortizationOfSecurities',
    'AssetImpairmentCharge',
    'BeginningCashPosition',
    'CapitalExpenditure',
    'CapitalExpenditureReported',
    'CashDividendsPaid',
    'CashFlowFromContinuingFinancingActivities',
    'CashFlowFromContinuingInvestingActivities',
    'CashFlowFromContinuingOperatingActivities',
    'CashFlowFromDiscontinuedOperation',
    'CashFlowsfromusedinOperatingActivitiesDirect',
    'CashFromDiscontinuedFinancingActivities',
    'CashFromDiscontinuedInvestingActivities',
    'CashFromDiscontinuedOperatingActivities',
    'ChangeInAccountPayable',
    'ChangeInAccruedExpense',
    'ChangeInCashSupplementalAsReported',
    'ChangeInDividendPayable',
    'ChangeInIncomeTaxPayable',
    'ChangeInInterestPayable',
    'ChangeInInventory',
    'ChangeInOtherCurrentAssets',
    'ChangeInOtherCurrentLiabilities',
    'ChangeInOtherWorkingCapital',
    'ChangeInPayable',
    'ChangeInPayablesAndAccruedExpense',
    'ChangeInPrepaidAssets',
    'ChangeInReceivables',
    'ChangeInTaxPayable',
    'ChangeInWorkingCapital',
    'ChangesInAccountReceivables',
    'ChangesInCash',
    'ClassesofCashPayments',
    'ClassesofCashReceiptsfromOperatingActivities',
    'CommonStockDividendPaid',
    'CommonStockIssuance',
    'CommonStockPayments',
    'DeferredIncomeTax',
    'DeferredTax',
    'Depletion',
    'Depreciation',
    'DepreciationAmortizationDepletion',
    'DepreciationAndAmortization',
    'DividendPaidCFO',
    'DividendReceivedCFO',
    'DividendsPaidDirect',
    'DividendsReceivedCFI',
    'DividendsReceivedDirect',
    'DomesticSales',
    'EarningsLossesFromEquityInvestments',
    'EffectOfExchangeRateChanges',
    'EndCashPosition',
    'ExcessTaxBenefitFromStockBasedCompensation',
    'FinancingCashFlow',
    'ForeignSales',
    'FreeCashFlow',
    'GainLossOnInvestmentSecurities',
    'GainLossOnSaleOfBusiness',
    'GainLossOnSaleOfPPE',
    'IncomeTaxPaidSupplementalData',
    'InterestPaidCFF',
    'InterestPaidCFO',
    'InterestPaidDirect',
    'InterestPaidSupplementalData',
    'InterestReceivedCFI',
    'InterestReceivedCFO',
    'InterestReceivedDirect',
    'InvestingCashFlow',
    'IssuanceOfCapitalStock',
    'IssuanceOfDebt',
    'LongTermDebtIssuance',
    'LongTermDebtPayments',
    'NetBusinessPurchaseAndSale',
    'NetCommonStockIssuance',
    'NetForeignCurrencyExchangeGainLoss',
    'NetIncome',
    'NetIncomeFromContinuingOperations',
    'NetIntangiblesPurchaseAndSale',
    'NetInvestmentPropertiesPurchaseAndSale',
    'NetInvestmentPurchaseAndSale',
    'NetIssuancePaymentsOfDebt',
    'NetLongTermDebtIssuance',
    'NetOtherFinancingCharges',
    'NetOtherInvestingChanges',
    'NetPPEPurchaseAndSale',
    'NetPreferredStockIssuance',
    'NetShortTermDebtIssuance',
    'OperatingCashFlow',
    'OperatingGainsLosses',
    'OtherCashAdjustmentInsideChangeinCash',
    'OtherCashAdjustmentOutsideChangeinCash',
    'OtherCashPaymentsfromOperatingActivities',
    'OtherCashReceiptsfromOperatingActivities',
    'OtherNonCashItems',
    'PaymentsonBehalfofEmployees',
    'PaymentstoSuppliersforGoodsandServices',
    'PensionAndEmployeeBenefitExpense',
    'PreferredStockDividendPaid',
    'PreferredStockIssuance',
    'PreferredStockPayments',
    'ProceedsFromStockOptionExercised',
    'ProvisionandWriteOffofAssets',
    'PurchaseOfBusiness',
    'PurchaseOfIntangibles',
    'PurchaseOfInvestment',
    'PurchaseOfInvestmentProperties',
    'PurchaseOfPPE',
    'ReceiptsfromCustomers',
    'ReceiptsfromGovernmentGrants',
    'RepaymentOfDebt',
    'RepurchaseOfCapitalStock',
    'SaleOfBusiness',
    'SaleOfIntangibles',
    'SaleOfInvestment',
    'SaleOfInvestmentProperties',
    'SaleOfPPE',
    'ShortTermDebtIssuance',
    'ShortTermDebtPayments',
    'StockBasedCompensation',
    'TaxesRefundPaid',
    'TaxesRefundPaidDirect',
    'UnrealizedGainLossOnInvestmentSecurities',
  ],
  valuation: [
    'ForwardPeRatio',
    'PsRatio',
    'PbRatio',
    'EnterprisesValueEBITDARatio',
    'EnterprisesValueRevenueRatio',
    'PeRatio',
    'MarketCap',
    'EnterpriseValue',
    'PegRatio',
  ],
};

/**
 * Time argument configurations for fundamental data queries.
 */
export const FUNDAMENTALS_TIME_ARGS: Record<string, { prefix: string; period_type: string }> = {
  a: { prefix: 'annual', period_type: '12M' },
  q: { prefix: 'quarterly', period_type: '3M' },
  m: { prefix: 'monthly', period_type: '1M' },
};

/**
 * Corporate event types for significant developments.
 */
export const CORPORATE_EVENTS = [
  'sigdev_corporate_guidance',
  'sigdev_performance',
  'sigdev_corporate_deals',
  'sigdev_expansion_new_markets_new_units',
  'sigdev_products',
  'sigdev_ownership_control',
  'sigdev_financing',
  'sigdev_litigation_regulatory',
  'sigdev_accounting_issues',
  'sigdev_restructuring_reorganization_related',
  'sigdev_reference',
  'sigdev_special_events',
  'sigdev_environment',
];
